image: yardinternet/php7.2-composer

pipelines:
  custom:
    manually:
      - step:
          name: unit test
          caches:
            - composer
            - vendor-directory
          script:
            - composer install --no-interaction --no-progress --prefer-dist --ignore-platform-reqs
            - ./vendor/bin/phpunit --testsuite "Unit Test Suite"
  branches:
    "{master,develop}":
      - step:
          name: unit test
          caches:
            - composer
            - vendor-directory
          script:
            - composer install --no-interaction --no-progress --prefer-dist --ignore-platform-reqs
            - ./vendor/bin/phpunit --testsuite "Unit Test Suite"

definitions:
  caches:
    vendor-directory: vendor
