image: yardinternet/php7.2-composer

pipelines:
  custom:
    manually:
      - step:
          name: unit test
          caches:
            - composer
            - vendor-directory
          script:
            - composer install --no-interaction --no-progress --prefer-dist --ignore-platform-reqs
            - ./vendor/bin/phpunit --testsuite "Unit Test Suite"
  branches:
    "{master,develop}":
      - step:
          name: unit test
          caches:
            - composer
            - vendor-directory
          script:
            - composer install --no-interaction --no-progress --prefer-dist --ignore-platform-reqs
            - ./vendor/bin/phpunit --testsuite "Unit Test Suite"
      # - step:
      #     name: Deploy docs to production
      #     caches:
      #       - composer
      #       - vendor-directory
      #     deployment: production
      #     script:
      #       - apt-get update && apt-get install -y git openssh-server rsync
      #       - composer docs
      #       - ssh webdev@web11.yard.nl mkdir -p /data/www/docs.openwebconcept.nl/htdocs/plugins/base && rsync -avH ./docs/* -e "ssh" webdev@web11.yard.nl:/data/www/docs.openwebconcept.nl/htdocs/plugins/base

definitions:
  caches:
    vendor-directory: vendor
