image: yardinternet/php7.2-composer

pipelines:
  custom:
    manually:
      - step:
          name: unit test
          caches:
            - composer
            - vendor-directory
          script:
            - composer update  --no-interaction --no-progress --prefer-dist --no-scripts
            - ./vendor/bin/phpunit --testsuite "Unit Test"
  branches:
    "{master,develop}":
      - step:
          name: unit test
          caches:
            - composer
            - vendor-directory
          script:
            - composer update  --no-interaction --no-progress --prefer-dist --no-scripts
            - ./vendor/bin/phpunit --testsuite "Unit Test"

definitions:
  caches:
    vendor-directory: vendor
