image: oktupol/bitbucket-pipelines-php71

pipelines:
  master:
    - step:
        caches:
          - composer
        script:
          - service mysql start
          - composer install --no-interaction --no-progress --prefer-dist
          - chmod +x bin/install-wp-tests.sh
          - bin/install-wp-tests.sh wordpress_test root root 127.0.0.1 latest
          - ./vendor/bin/phpunit